package br.coop.integrada.api.pa.domain.modelDto.producao;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data @NoArgsConstructor @AllArgsConstructor
public class ParametroProducaoDto implements Serializable {
    private static final long serialVersionUID = 1L;

    private String codEspeciePermuta;
    private String tabelaFixar;
    private String contaTransitoria;
    private String contaDevFechar;
    private String centroCustoAva;
    private BigDecimal taxaAdministracao;
    private BigDecimal taxaRetencao;
    private BigDecimal taxaInssPj;
    private BigDecimal taxaInssPf;
    private BigDecimal taxaSenarPf;
    private String codEspecieQuebra;
    private String codEspecieSeguro;
    private String codEspecieManutencao;
    private String codEspecieSecagem;
    private String codEspecieAdmin;
    private String codEspecieCapital;
    private String codEspecieSenar;
    private String codEspecieFam;
    private String codEspecieFechamento;
    private Integer diaVencimentoInss;
    private Integer diaVencimentoSenar;
    private BigDecimal taxaSenarPj;
    private BigDecimal taxaExtra;
    private String codEspecieCapitalEspecial;
    private String codEspecieOutrasTaxas;
    private String codEspecieTaxasExtra;
    private String codEspecieKit;
    private String codPaisInss;
    private String codUfInss;
    private String codImpostoInss;
    private String codClassificacaoInss;
    private String codPaisSenar;
    private String codUfSenar;
    private String codImpostoSenar;
    private String codClassificacaoSenar;
    private String codClassificacaoSoSenar;
    private String codEspecieArmazen;
    private String codEspecieRecepcao;
    private String sementeContaTratadaEntrada;
    private String sementeContaTratadaSaida;
    private String sementeSerieTratadaEntrada;
    private String sementeSerieTratadaSaida;
    private String sementeDepositoTratadaEntrada;
    private String sementeDepositoTratadaSainda;
    private String sementeCentroCustoTratadaEntrada;
    private String sementeCentroCustoTratadaSaida;
    private String codPaisGilrat;
    private String codUfGilrat;
    private String codImpostoGilrat;
    private String codClassificacaoGilrat;
    private Integer qtdAnosFixacao;
    private String bayerUsuario;
    private String bayerSenha;
    private String codEspecieEpc;
    private String tipoFluxoCooperado;
    private String tipoFluxoCooperadoDescricao;
    private String planoContaContabilCooperado;
    private String planoContaContabilCooperadoDescricao;
    private String contaContabilCooperado;
    private String contaContabilCooperadoDescricao;
    private String tipoFluxoTerceiro;
    private String tipoFluxoTerceiroDescricao;
    private String planoContaContabilTerceiro;
    private String planoContaContabilTerceiroDescricao;
    private String contaContabilTerceiro;
    private String contaContabilTerceiroDescricao;
    private String contaContabilTransitoria;
    private String contaContabilTransitoriaDescricao;
    private Integer qtdMaxBxaMassa;
    private String codEspecieSenarSemente;
    private String codEspecieInssSemente;
    private BigDecimal taxaGilratPj;
    private BigDecimal taxaGilratPf;
    private String codEspecieGilrat;
    private String codEspecieInss;
}
